# Generated by Django 5.2.7 on 2025-10-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_file_upload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file_upload',
            table='FILE UPLOAD',
        ),
    ]
