# Generated by Django 5.2.7 on 2025-10-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
