# Generated by Django 5.2.7 on 2025-10-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leader',
            table='Leader table',
        ),
    ]
