# Generated by Django 5.2.7 on 2025-10-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_m', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
