# Generated by Django 5.2.7 on 2025-10-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_m', '0004_department_student1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='DEPARTMENT',
        ),
    ]
