# Generated by Django 5.2.7 on 2025-10-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0002_alter_stud_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20, verbose_name='Sure Name')),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'EMPLOYEE DATA',
            },
        ),
    ]
