# Generated by Django 5.2.7 on 2025-10-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0004_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_upload',
            old_name='image',
            new_name='photo',
        ),
    ]
